FROM node:22-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --force

COPY . .

RUN npm run build --prod

FROM nginx:alpine

COPY --from=build /usr/src/app/dist/demo/browser /usr/share/nginx/html

RUN rm -f /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN ls -la /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]