FROM node:22-alpine

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Copy source code
COPY . .

# Expose port
EXPOSE 4200

# Start the application
CMD ["npm", "start", "--", "--host", "0.0.0.0"]