apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api
  name: catbit-api
spec:
  type: LoadBalancer
  ports:
    - name: "api"
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: catbit-api
