apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db
  name: catbit-db
spec:
  type: LoadBalancer
  ports:
    - name: "db"
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    io.kompose.service: db
