apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: catbit-web
  name: catbit-web
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: catbit-web
